# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 395a65142beae4c9eb94038c6336670b9907f7c1574802c202e0826285fc4f590442e4e6c4ac5c887023e4c6c8d89f2ae155e618679d68fd596e35d610137204

test:
  secret_key_base: 482585fc0b716e8bd0a01297ebe63fef99d4708b08f09d2fc265776d2d3f6871832a46471065547100141cdcc463daaea4ae17f1d87965cdb7b1dc2aaee586ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
